### ISSUE TITLE
ERROR during install tailwind config 

### ISSUE THREAD

**Issue by kyle-hensoon** [tailwindcss/docs#475]
hello , i try to install tailwind config with this command  " npx tailwind init tailwind.js --full
 " but it show a error

internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for 'C:\Users\mosta\Desktop\gitjob\node_modules\colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\mosta\Desktop\gitjob\node_modules\autoprefixer\lib\autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}

**Comment by estevanmaito** [comment]
This is the docs repo. You should create your question in the main repo https://github.com/tailwindcss/tailwindcss

ps: you're using the wrong package, it should be `tailwindcss` and not just `tailwind` https://tailwindcss.com/docs/installation#3-create-your-tailwind-config-file-optional
